In [16]:
%load_ext autoreload
%autoreload 2
from self_learn import LogisticRegression
from utils import *

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [17]:
%store -r X_train
%store -r X_val
%store -r y_train
%store -r y_val

In [26]:
logreg = LogisticRegression(num_epochs=1000,
                            learning_rate=0.01,
                            regularization="L2", 
                            lambda_reg=0.1, 
                            gamma=2,
                            validation=True,
                            class_weights=[0.54176468, 7.36963696, 1.66483665],
                            #alpha = [0.08, 0.50, 0.1],
                            logging_notes="FE: Squared transformation, trigonometric temporal features, class weights",
                            logging_tag="baseline_logreg",
                            verbose=1)
logreg.fit(X = X_train.values, 
          y = y_train.values,
          X_val = X_val.values,
          y_val = y_val.values)

Epoch 0, Loss: 11972.678461449948, Train Accuracy: 0.31615755989712585, Val Accuracy: 0.24958333333333332
Epoch 100, Loss: 6780.022936765312, Train Accuracy: 0.46965663493209403, Val Accuracy: 0.505
Epoch 200, Loss: 6215.506394396225, Train Accuracy: 0.5093173306862789, Val Accuracy: 0.5775
Epoch 300, Loss: 5972.109769188968, Train Accuracy: 0.5247484546315931, Val Accuracy: 0.5991666666666666
Epoch 400, Loss: 5832.579438779899, Train Accuracy: 0.5373370031132969, Val Accuracy: 0.6129166666666667
Epoch 500, Loss: 5740.4041395218555, Train Accuracy: 0.5451879258223165, Val Accuracy: 0.6204166666666666
Epoch 600, Loss: 5674.082681133758, Train Accuracy: 0.550692595767721, Val Accuracy: 0.625
Epoch 700, Loss: 5623.58665857722, Train Accuracy: 0.5545278166313224, Val Accuracy: 0.6283333333333333
Epoch 800, Loss: 5583.584451431482, Train Accuracy: 0.5586788792131029, Val Accuracy: 0.6283333333333333
Epoch 900, Loss: 5550.9663621920545, Train Accuracy: 0.5615665749221675, Val Accuracy: 0.63


In [27]:
y_pred = logreg.predict(X_val.values)
accuracy = (y_val == y_pred).mean()
print(np.unique(y_pred))
print(f'Accuracy: {accuracy:.2%}')

[0 1 2]
Accuracy: 63.38%


In [28]:
get_classification_report(y_val, y_pred)

1. The F-1 score of the model 0.5634904716579431

2. The recall score of the model 0.829806398141033

3. Classification report 
               precision    recall  f1-score   support

           0       0.99      0.53      0.69      1836
           1       0.21      0.97      0.35       112
           2       0.49      0.99      0.66       452

    accuracy                           0.63      2400
   macro avg       0.56      0.83      0.56      2400
weighted avg       0.86      0.63      0.67      2400
 

4. Confusion matrix 
 [[964 406 466]
 [  3 109   0]
 [  4   0 448]] 

